In [1]:
import duckdb
import pandas as pd

In [2]:
# Create Development Database
sql_query = '''
SHOW TABLES
'''

# Connect to the DuckDB database and execute the query
with duckdb.connect('data/dev_leads_database.db') as con:
    # Display the query result as a DataFrame
    display(con.sql(sql_query).df())

                           name
0        fct_deduplicated_leads
1               fct_delta_leads
2                fct_lead_loads
3   fct_lead_source_performance
4         fct_lead_work_metrics
5                fct_sfdc_leads
6      int_unified_source_leads
7                 lead_source_1
8                 lead_source_2
9                 lead_source_3
10           my_first_dbt_model
11          my_second_dbt_model
12                   sfdc_leads
13            stg_lead_source_1
14            stg_lead_source_2
15            stg_lead_source_3

In [7]:
sql_query_import_1 = '''

CREATE OR REPLACE TABLE lead_source_1 AS 
SELECT *
FROM read_csv_auto('data/raw_source_1.csv', normalize_names=True)

'''

sql_query_import_2 = '''

CREATE OR REPLACE TABLE lead_source_2 AS 
SELECT *
FROM read_csv_auto('data/raw_source_2.csv', normalize_names=True)

'''

sql_query_import_3 = '''

CREATE OR REPLACE TABLE lead_source_3 AS 
SELECT *
FROM read_csv_auto('data/raw_source_3.csv', normalize_names=True)

'''

sql_query_import_4 = '''

CREATE OR REPLACE TABLE sfdc_leads AS 
SELECT *
FROM read_csv_auto('data/raw_sfdc_leads.csv', normalize_names=True)

'''

with duckdb.connect('data/dev_leads_database.db') as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)
    con.sql(sql_query_import_3)
    con.sql(sql_query_import_4)

In [11]:
# View raw data imports
sql_query = '''
SHOW TABLES
'''

# Connect to the DuckDB database and execute the query
with duckdb.connect('data/dev_leads_database.db') as con:
    # Display the query result as a DataFrame
    display(con.sql(sql_query).df())

                           name
0        fct_deduplicated_leads
1               fct_delta_leads
2                fct_lead_loads
3   fct_lead_source_performance
4         fct_lead_work_metrics
5                fct_sfdc_leads
6      int_unified_source_leads
7                 lead_source_1
8                 lead_source_2
9                 lead_source_3
10           my_first_dbt_model
11          my_second_dbt_model
12                   sfdc_leads
13            stg_lead_source_1
14            stg_lead_source_2
15            stg_lead_source_3

In [13]:
# View raw data imports
sql_query = '''

select * from int_unified_source_leads limit 5

'''

# Connect to the DuckDB database and execute the query
with duckdb.connect('data/dev_leads_database.db') as con:
    # Display the query result as a DataFrame
    display(con.sql(sql_query).df())

,company,accepts_financial_aid,ages_served,capacity,license_type,license_status,license_issued_date,certificate_expiration_date,address1,address2,...,first_name,last_name,title,email,schedule,webstie_address,facility_type,lead_source,min_age,max_age
0,SUNSHINE ACADEMY PRE-SCHOOL,None,None,NaN,CENTER,Active,2013-12-01,2023-11-30,150 N. WILLOW ST MESQUITE,NaN,...,JANEECE,NOEL,Other,None,NaN,NaN,NaN,Source 1,NaN,NaN
1,SUNRISE CHILDREN'S FOUNDATION EARLY HEAD START...,None,None,NaN,CENTER,Active,2017-01-01,2023-10-31,2845 MOHAWK ST LAS VEGAS,NaN,...,TANIA,NICOLE PINEDA,Director,None,NaN,NaN,NaN,Source 1,NaN,NaN
2,BOLD AND BRIGHT ACADEMY LLC,None,None,NaN,FAMILY CARE,Active,2020-07-01,2024-06-30,6036 ATLANTIS DREAM AVE LAS VEGAS,NaN,...,BETHANY,JOHNSON,Owner,None,NaN,NaN,NaN,Source 1,NaN,NaN
3,DISCOVERY GARDENS CHILDCARE L.L.C.,None,None,NaN,CENTER (PROVISIONAL),Active,2017-05-18,2023-07-31,555 PAGE ST LAS VEGAS,NaN,...,SHERRITA,MYERS,Other,None,NaN,NaN,NaN,Source 1,NaN,NaN
4,THE LITTLE EXPLORERS LLC,None,None,NaN,GROUP CARE,Active,2018-02-07,2024-01-31,470 GYPSUM DRIVE SPRING CREEK,NaN,...,KYLA,HANNAH,Owner,None,NaN,NaN,NaN,Source 1,NaN,NaN

In [15]:
# View raw data imports
sql_query = '''

select * from "dev_leads_database"."main_dbt_test__audit"."generic_not_null_int_unified_source_leads_first_name" limit 5

'''

# Connect to the DuckDB database and execute the query
with duckdb.connect('data/dev_leads_database.db') as con:
    # Display the query result as a DataFrame
    display(con.sql(sql_query).df())

,company,accepts_financial_aid,ages_served,capacity,license_type,license_status,license_issued_date,certificate_expiration_date,address1,address2,...,first_name,last_name,title,email,schedule,webstie_address,facility_type,lead_source,min_age,max_age
0,"K"" Street Learning Center LLC""",None,"Infant (0 - 11 months), Toddler (12 - 23 month...",82,Licensed Center - Child Care Program,Full Permit,2011-10-13,NaT,19290 K ST,NaN,...,None,None,None,sylvia@kstreetlearningcenter.com,NaN,NaN,NaN,Source 3,0,60
1,1 on 1 Childcare Academy,None,"Infant (0 - 11 months), Toddler (12 - 23 month...",33,Licensed Center - Child Care Program,Full Permit,2022-07-01,NaT,11925 GLOGER ST,NaN,...,None,None,None,1on1childcareacademy@gmail.com,NaN,NaN,NaN,Source 3,0,60
2,1.2..me Kidz,None,"Infant (0 - 11 months), Toddler (12 - 23 month...",81,Licensed Center - Child Care Program,Full Permit,2019-03-21,NaT,1222 BABCOCK RD,NaN,...,None,None,None,kidz1.2me@yahoo.com,NaN,NaN,NaN,Source 3,0,60
3,123 Sunshine Academy,None,"Infant (0 - 11 months), Toddler (12 - 23 month...",12,Licensed Child-Care Home,Full Permit,2018-02-01,NaT,15303 E ANTONE CIR,NaN,...,None,None,None,None,NaN,NaN,NaN,Source 3,0,60
4,123-Abc Learning Center,None,", Toddler (12 - 23 months), Preschool (24 - 48...",12,Licensed Child-Care Home,Full Permit,2022-06-14,NaT,5418 BAKERSFIELD ST,NaN,...,None,None,None,lorena123abc@aol.com,NaN,NaN,NaN,Source 3,12,60

In [16]:
# Create Production Database
sql_query = '''
SHOW TABLES
'''

# Connect to the DuckDB database and execute the query
with duckdb.connect('data/prod_leads_database.db') as con:
    # Display the query result as a DataFrame
    display(con.sql(sql_query).df())

Empty DataFrame
Columns: [name]
Index: []

In [17]:
sql_query_import_1 = '''

CREATE OR REPLACE TABLE lead_source_1 AS 
SELECT *
FROM read_csv_auto('data/raw_source_1.csv', normalize_names=True)

'''

sql_query_import_2 = '''

CREATE OR REPLACE TABLE lead_source_2 AS 
SELECT *
FROM read_csv_auto('data/raw_source_2.csv', normalize_names=True)

'''

sql_query_import_3 = '''

CREATE OR REPLACE TABLE lead_source_3 AS 
SELECT *
FROM read_csv_auto('data/raw_source_3.csv', normalize_names=True)

'''

sql_query_import_4 = '''

CREATE OR REPLACE TABLE sfdc_leads AS 
SELECT *
FROM read_csv_auto('data/raw_sfdc_leads.csv', normalize_names=True)

'''

with duckdb.connect('data/prod_leads_database.db') as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)
    con.sql(sql_query_import_3)
    con.sql(sql_query_import_4)

In [3]:
# Create Production Database
sql_query = '''
SHOW TABLES
'''

# Connect to the DuckDB database and execute the query
with duckdb.connect('data/prod_leads_database.db') as con:
    # Display the query result as a DataFrame
    display(con.sql(sql_query).df())

                           name
0        fct_deduplicated_leads
1               fct_delta_leads
2                fct_lead_loads
3   fct_lead_source_performance
4         fct_lead_work_metrics
5                fct_sfdc_leads
6                 lead_source_1
7                 lead_source_2
8                 lead_source_3
9            my_first_dbt_model
10          my_second_dbt_model
11                   sfdc_leads
12            stg_lead_source_1
13            stg_lead_source_2
14            stg_lead_source_3

In [1]:
import pandas as pd
import duckdb

In [3]:
sql_query = ''' show tables '''

with duckdb.connect('data/dev_leads_database.db') as con: 
    display(con.sql(sql_query).df())

                           name
0        fct_deduplicated_leads
1               fct_delta_leads
2                fct_lead_loads
3   fct_lead_source_performance
4         fct_lead_work_metrics
5                fct_sfdc_leads
6      int_unified_source_leads
7                 lead_source_1
8                 lead_source_2
9                 lead_source_3
10           my_first_dbt_model
11          my_second_dbt_model
12                   sfdc_leads
13            stg_lead_source_1
14            stg_lead_source_2
15            stg_lead_source_3

In [9]:
sql_query = ''' select phone, count(*) from fct_delta_leads group by 1 having count(*) > 1 '''

with duckdb.connect('data/dev_leads_database.db') as con:
    display(con.sql(sql_query).df())

        phone  count_star()
0  7023083384             3
1  6302129413             2

In [11]:
sql_query = ''' select * from stg_lead_source_2 limit 5 '''

with duckdb.connect('data/dev_leads_database.db') as con:
    display(con.sql(sql_query).df())

,company,license_type,accepts_financial_aid,license_status,phone,email,address1,address2,city,state,...,primary_caregiver,cleaned_name,first_name,last_name,title,license_issued_date,ages_served,AA2,AA3,aa4
0,"HELLSTROM, ELIZABETH",CHILD CARE FAMILY - K820055232,None,2 Star Level Program,209 7471797,doubletroubledaycareok@gmail.com,None,NaN,YUKON,OK,...,Elizabeth Hellstrom\n \n Primary Caregiver,Elizabeth Hellstrom Primary Caregiver,Elizabeth,Hellstrom,Primary Caregiver,2020-09-02,"Toddlers (12-23 months; 1yr.), Preschool (24-4...",Preschool (24-48 months; ),None,None
1,"BRIGGS, DASHESHIA DBA DEELIGHTFUL LEARNING STA...",CHILD CARE FAMILY - K820055484,Accepts Subsidy,5 Star Level Program,214 7337201,dasheshiab@gmail.com,None,NaN,OKLAHOMA CITY,OK,...,Dasheshia Briggs\n \n Primary Caregiver,Dasheshia Briggs Primary Caregiver,Dasheshia,Briggs,Primary Caregiver,2020-12-18,"Infants (0-11 months), Toddlers (12-23 months;...",Toddlers (12-23 months; ),Preschool (24-48 months; ),None
2,"MUDDY PUDDLES LEARNING SPACE, LLC",CHILD CARE CENTER - K830056761,Accepts Subsidy,3 Star Level Program,216 7035825,symira24@gmail.com,None,NaN,BROKEN ARROW,OK,...,Symira Clifton\n \n Director,Symira Clifton Director,Symira,Clifton,Director,2023-05-02,"Infants (0-11 months), Toddlers (12-23 months;...",Toddlers (12-23 months; ),Preschool (24-48 months; ),School-age (60 monhts)
3,"CLIFTON, SYMIRA DBA MUDDY PUDDLES LEARNING SPA...",CHILD CARE FAMILY - K820056097,Accepts Subsidy,5 Star Level Program,216 7035825,symira24@gmail.com,None,NaN,TULSA,OK,...,Symira Clifton\n \n Primary Caregiver,Symira Clifton Primary Caregiver,Symira,Clifton,Primary Caregiver,2022-05-25,"Infants (0-11 months), Toddlers (12-23 months;...",Toddlers (12-23 months; ),Preschool (24-48 months; ),School-age (60 monhts)
4,"COFFIN, CASANDRA DBA LEAPS OF FUN LLC",CHILD CARE FAMILY - K820055740,Accepts Subsidy,4 Star Level Program,307 7519334,cassie.ccg@outlook.com,None,NaN,OWASSO,OK,...,Casandra Coffin\n \n Primary Caregiver,Casandra Coffin Primary Caregiver,Casandra,Coffin,Primary Caregiver,2021-09-02,"Infants (0-11 months), Toddlers (12-23 months;...",Toddlers (12-23 months; ),Preschool (24-48 months; ),None

In [12]:
sql_query = ''' select * from fct_lead_source_performance '''

with duckdb.connect('data/dev_leads_database.db') as con:
    display(con.sql(sql_query).df())

          lead_source  total_leads  converted_leads  conversion_rate
0     Proactive Trial            2                0              0.0
1                 Web            8                0              0.0
2  Marketing Research            2                0              0.0
3       List Purchase            1                0              0.0
4                None            1                0              0.0
5                 TAM           25                0              0.0